# Generated by Django 5.2.1 on 2025-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('guideline', 'Guideline'), ('example', 'Example')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document_type', 'title', 'order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Principle',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
