# Generated by Django 6.0.1 on 2026-01-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_remove_legacy_add_newsexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='processed_content',
            field=models.TextField(blank=True, help_text='التعليمات المعالجة والمترجمة للإنجليزية - تُستخدم بواسطة الموديل'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='content',
            field=models.TextField(help_text='التعليمات الأصلية بالعربي'),
        ),
    ]
